"""
This script compiles all .station JSON files into appropriate vATIS profiles.
Each vATIS profile must exist in the root directory and be defined in vars below.
Each vATIS profile must contain at least a defined "name" key.
Example:
    {
        "name": "Los Angeles ARTCC (ZLA)"
    }
Ideally, the station profile also includes the "id" key.
"""

import json
import glob

# Search for station files in all sub-folders of ./stations/
ALL_STATIONS = sorted(glob.glob("./stations/*/*.station"))

# The ZLA profile uses specific airports regardless of TRACON or folder.
ZLA_PROFILE = "./vATIS-Profile-ZLA.json"
ZLA_PROFILE_AIRPORTS = ['KBUR', 'KLAS', 'KLAX', 'KONT', 'KPSP', 'KSAN', 'KSBA', 'KSNA', 'KVNY']

# TRACON profiles based on the sub-folder name in ./stations/.
JCF_PROFILE = "./vATIS-Profile-JCF.json"
L30_PROFILE = "./vATIS-Profile-L30.json"
SBA_PROFILE = "./vATIS-Profile-SBA.json"
SCT_PROFILE = "./vATIS-Profile-SCT.json"

# These airports will not be included in any profile.
EXCLUDE_AIRPORTS = []

def filter_all_stations():
    """ Filters airports in EXCLUDE_AIRPORTS """
    available_stations = ALL_STATIONS
    for available_stations_index, each_station in enumerate(available_stations):
        for each_exclude_airport in EXCLUDE_AIRPORTS:
            if each_exclude_airport in each_station:
                available_stations.pop(available_stations_index)
    return available_stations

def build_station_list(search_query, input_list):
    """ Builds a list of all station files """
    output_list = []
    for each_station in input_list:
        for each_search_query in search_query:
            if each_search_query in each_station:
                output_list.append(each_station)
    return output_list

def build_profile(input_stations, vatis_profile):
    """
    input_stations: A list of station files using relative path (ex: ./stations/SCT/KLAX.station).
        This is generated by build_station_list().
    vatis_profile: The vATIS profile JSON.
    This function merges station files and then injects them into an existing vATIS profile.
    A base profile MUST exist for this to work. This does not build JSON files.
    """
    merged_stations = []
    # Opens each station file from input_stations (a list of files) and appends to merged_stations
    for each_station in input_stations:
        with open(each_station, "r", encoding="utf-8") as station_file:
            station_data = json.load(station_file)
            merged_stations.append(station_data)

    # Opens and loads the vATIS profile
    with open(vatis_profile, "r", encoding="utf-8") as vatis_profile_file:
        vatis_profile_data = json.load(vatis_profile_file)

    # Writes merged_stations into "stations" key and saves the vATIS profile
    with open(vatis_profile, "w", encoding="utf-8") as vatis_profile_file:
        vatis_profile_data["stations"] = merged_stations
        json.dump(vatis_profile_data, vatis_profile_file, indent=2)

AVAILABLE_STATIONS = filter_all_stations()

# Build the ZLA profile
ZLA_PROFILE_STATIONS = build_station_list(ZLA_PROFILE_AIRPORTS, AVAILABLE_STATIONS)
build_profile(ZLA_PROFILE_STATIONS, ZLA_PROFILE)

# Build the JCF profile
JCF_PROFILE_STATIONS = build_station_list(['/JCF'], AVAILABLE_STATIONS)
build_profile(JCF_PROFILE_STATIONS, JCF_PROFILE)

# Build the L30 profile
L30_PROFILE_STATIONS = build_station_list(['/L30'], AVAILABLE_STATIONS)
build_profile(L30_PROFILE_STATIONS, L30_PROFILE)

# Build the SBA profile
SBA_PROFILE_STATIONS = build_station_list(['/SBA'], AVAILABLE_STATIONS)
build_profile(SBA_PROFILE_STATIONS, SBA_PROFILE)

# Build the SCT profile
SCT_PROFILE_STATIONS = build_station_list(['/SCT'], AVAILABLE_STATIONS)
build_profile(SCT_PROFILE_STATIONS, SCT_PROFILE)
