name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            vATIS-Profile-!(DEV-*)*.json
          generate_release_notes: true
          make_latest: true
